name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    # permissions:
      # packages: write
      # contents: read
    steps:
      - name: Check out this repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username williamtheakergusto --password-stdin
          
      - name: Build and push image
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8 -t williamtheakergusto/micromdm:latest --push .

      # - name: Push image to Github Container Registry
        # run: docker push ghcr.io/OWNER/IMAGE_NAME:latest
